name: CI - ArchLinux

on:
  push:
  pull_request:

jobs:
  build-with-arch:
    runs-on: "ubuntu-latest"
    container:
      image: archlinux/archlinux:base-devel
    steps:
    - run: pacman -Syu --noconfirm boost cmake eigen git ninja python-numpy python-scipy

    - uses: actions/checkout@v4
      with:
        submodules: true

    - run: cmake -B build -S . -DCMAKE_GENERATOR=Ninja
    - run: cmake --build build
    - run: cmake --build build -t test
